name: Build and deploy

on:
  workflow_dispatch:
  push:

jobs:
  buid-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
        cache: "pip"
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
    - name: Build SQLite database
      run: ./build-db.sh
    - name: Deploy to Vercel
      env:
        VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      run: |-
        datasette publish vercel scotrail.db \
          --token $VERCEL_TOKEN \
          --scope datasette \
          --project scotrail \
          --install datasette-mp3-audio \
          --metadata metadata.yml
